apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-qpev
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhpo-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-qpev@sha256:1a17b5fdded521aeef49c5bf5cb1dfbd7ca0e50e07dcaa8650eb832bbd7380fd
        name: my-go
        resources: {}
status: {}
